name: fleksa_assignment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # toast
  fluttertoast: ^8.0.8
  # networking libraries
  freezed: ^1.1.1
  flutter_bloc: ^8.0.1
  logger: ^1.1.0
  equatable: ^2.0.3
  pretty_dio_logger: ^1.1.1
  dio: ^4.0.4
  retrofit: ^3.0.1+1
  json_annotation: ^4.4.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
